dataset_path: data/final/power_tetouan_city_after_EDA.csv
target: z1_power_cons
test_size: 0.2
random_state: 42
model:
  type: RandomForestRegressor
  n_estimators: 50
  max_depth: 20
mlflow:
  tracking_uri: null
  experiment_name: equipo31-remote
